# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnSimpleBlogRedux' do
  inherit! :search_paths
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

end
